RUN_STRINGS = (
    "Now you see me, now you don't." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Huh? what? did they get away?",
    "Get back here!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

SLAP_GOJO_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Don't again dare to slap me.",
)

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \\(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
    "{user2} was shot by {user1}.",
    "{user2} walked into a cactus while trying to escape {user1}.",
    "{user2} drowned whilst trying to escape {user1}.",
    "{user2} fell into a patch of cacti.",
    "{user2} went up in flames.",
    "{user2} burned to death.",
    "{user2} was burnt to a crisp whilst fighting {user1}.",
    "{user2} was struck by lightning.",
    "{user2} was slain by {user1}.",
    "{user2} was killed by magic.",
    "{user2} starved to death.",
    "{user2} fell out of the world.",
    "{user2} was knocked into the void by {user1}.",
    "{user2}'s bones are scraped clean by the desolate wind.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} says goodbye to this cruel world.",
    "{user2} got rekt.",
    "{user2} was sawn in half by {user1}.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2}'s death put another notch in {user1}'s axe.",
    "{user2} died from {user1}'s mysterious tropical disease.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user2} was shot before being thrown out of a plane.",
    "{user2} has encountered an error.",
    "{user2} died and reincarnated as a goat.",
    "{user1} threw {user2} off a building.",
    "{user2} got a premature burial.",
    "{user1} spammed {user2}'s email.",
    "{user1} hit {user2} with a small, interstellar spaceship.",
    "{user1} put {user2} in check-mate.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} died of hospital gangrene.",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!.",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2}, to infinity and beyond."
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} exchanged {user2}'s life-force for a cup of chocolate.",
    "{user2} did a 69 with a cactus.",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user1} traveled to the future and spat on {user2}'s grave.",
    "{user2} died from talk-no-jutsu.",
    "{user2} was placed as a carpet for a stomp dance competition.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "{user1} learned why being a crocodile dentist was a bad idea.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
    "angry bird",
    "your ego",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = ("hits", "whacks", "slaps", "smacks", "bashes", "pats")

REACTIONS = (
    "( ͡° ͜ʖ ͡°)",
    "( . •́ _ʖ •̀ .)",
    "( ಠ ͜ʖ ಠ)",
    "( ͡ ͜ʖ ͡ )",
    "(ʘ ͜ʖ ʘ)",
    "ヾ(´〇`)ﾉ♪♪♪",
    "ヽ(o´∀`)ﾉ♪♬",
    "♪♬((d⌒ω⌒b))♬♪",
    "└(＾＾)┐",
    "(￣▽￣)/♫•*¨*•.¸¸♪",
    "ヾ(⌐■_■)ノ♪",
    "乁( • ω •乁)",
    "♬♫♪◖(● o ●)◗♪♫♬",
    "(っ˘ڡ˘ς)",
    "( ˘▽˘)っ♨",
    "(　・ω・)⊃-[二二]",
    "(*´ー`)旦 旦(￣ω￣*)",
    "( ￣▽￣)[] [](≧▽≦ )",
    "(*￣▽￣)旦 且(´∀`*)",
    "(ノ ˘_˘)ノ　ζ|||ζ　ζ|||ζ　ζ|||ζ",
    "(ノ°∀°)ノ⌒･*:.｡. .｡.:*･゜ﾟ･*☆",
    "(⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿",
    "(∩` ﾛ ´)⊃━炎炎炎炎炎",
    "( ・∀・)・・・--------☆",
    "( -ω-)／占~~~~~",
    "○∞∞∞∞ヽ(^ー^ )",
    "(*＾＾)/~~~~~~~~~~◎",
    "((( ￣□)_／",
    "(ﾒ￣▽￣)︻┳═一",
    "ヽ( ･∀･)ﾉ_θ彡☆Σ(ノ `Д´)ノ",
    "(*`0´)θ☆(メ°皿°)ﾉ",
    "(; -_-)――――――C<―_-)",
    "ヽ(>_<ヽ) ―⊂|=0ヘ(^‿^ )",
    "(҂` ﾛ ´)︻デ═一 ＼(º □ º l|l)/",
    "/( .□.)＼ ︵╰(°益°)╯︵ /(.□. /)",
    "(`⌒*)O-(`⌒´Q)",
    "(っ•﹏•)っ ✴==≡눈٩(`皿´҂)ง",
    "ヾ(・ω・)メ(・ω・)ノ",
    "(*^ω^)八(⌒▽⌒)八(-‿‿- )ヽ",
    "ヽ( ⌒ω⌒)人(=^‥^= )ﾉ",
    "｡*:☆(・ω・人・ω・)｡:゜☆｡",
    "(°(°ω(°ω°(☆ω☆)°ω°)ω°)°)",
    "(っ˘▽˘)(˘▽˘)˘▽˘ς)",
    "(*＾ω＾)人(＾ω＾*)",
    r"＼(▽￣ \ (￣▽￣) / ￣▽)／",
    "(￣Θ￣)",
    "＼( ˋ Θ ´ )／",
    "( ´(00)ˋ )",
    "＼(￣(oo)￣)／",
    "／(≧ x ≦)＼",
    "／(=･ x ･=)＼",
    "(=^･ω･^=)",
    "(= ; ｪ ; =)",
    "(=⌒‿‿⌒=)",
    "(＾• ω •＾)",
    "ଲ(ⓛ ω ⓛ)ଲ",
    "ଲ(ⓛ ω ⓛ)ଲ",
    "(^◔ᴥ◔^)",
    "[(－－)]..zzZ",
    "(￣o￣) zzZZzzZZ",
    "(＿ ＿*) Z z z",
    "☆ﾐ(o*･ω･)ﾉ",
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "ε===(っ≧ω≦)っ",
    "__φ(．．)",
    "ヾ( `ー´)シφ__",
    "( ^▽^)ψ__",
    "|･ω･)",
    "|д･)",
    "┬┴┬┴┤･ω･)ﾉ",
    "|･д･)ﾉ",
    "(*￣ii￣)",
    "(＾〃＾)",
    "m(_ _)m",
    "人(_ _*)",
    "(シ. .)シ",
    "(^_~)",
    "(>ω^)",
    "(^_<)〜☆",
    "(^_<)",
    "(づ￣ ³￣)づ",
    "(⊃｡•́‿•̀｡)⊃",
    "⊂(´• ω •`⊂)",
    "(*・ω・)ﾉ",
    "(^-^*)/",
    "ヾ(*'▽'*)",
    "(^０^)ノ",
    "(*°ｰ°)ﾉ",
    "(￣ω￣)/",
    "(≧▽≦)/",
    "w(°ｏ°)w",
    "(⊙_⊙)",
    "(°ロ°) !",
    "∑(O_O;)",
    "(￢_￢)",
    "(¬_¬ )",
    "(↼_↼)",
    "(￣ω￣;)",
    "┐('～`;)┌",
    "(・_・;)",
    "(＠_＠)",
    "(•ิ_•ิ)?",
    "ヽ(ー_ー )ノ",
    "┐(￣ヘ￣)┌",
    "┐(￣～￣)┌",
    "┐( ´ д ` )┌",
    "╮(︶▽︶)╭",
    "ᕕ( ᐛ )ᕗ",
    "(ノωヽ)",
    "(″ロ゛)",
    "(/ω＼)",
    "(((＞＜)))",
    "~(>_<~)",
    "(×_×)",
    "(×﹏×)",
    "(ノ_<。)",
    "(μ_μ)",
    "o(TヘTo)",
    "( ﾟ，_ゝ｀)",
    "( ╥ω╥ )",
    "(／ˍ・、)",
    "(つω`｡)",
    "(T_T)",
    "o(〒﹏〒)o",
    "(＃`Д´)",
    "(・`ω´・)",
    "( `ε´ )",
    "(ﾒ` ﾛ ´)",
    "Σ(▼□▼メ)",
    "(҂ `з´ )",
    "٩(╬ʘ益ʘ╬)۶",
    "↑_(ΦwΦ)Ψ",
    "(ﾉಥ益ಥ)ﾉ",
    "(＃＞＜)",
    "(；￣Д￣)",
    "(￢_￢;)",
    "(＾＾＃)",
    "(￣︿￣)",
    "ヾ( ￣O￣)ツ",
    "(ᗒᗣᗕ)՞",
    "(ノ_<。)ヾ(´ ▽ ` )",
    "ヽ(￣ω￣(。。 )ゝ",
    "(ﾉ_；)ヾ(´ ∀ ` )",
    "(´-ω-`( _ _ )",
    "(⌒_⌒;)",
    "(*/_＼)",
    "( ◡‿◡ *)",
    "(//ω//)",
    "(￣▽￣*)ゞ",
    "(„ಡωಡ„)",
    "(ﾉ´ з `)ノ",
    "(♡-_-♡)",
    "(─‿‿─)♡",
    "(´ ω `♡)",
    "(ღ˘⌣˘ღ)",
    "(´• ω •`) ♡",
    "╰(*´︶`*)╯♡",
    "(≧◡≦) ♡",
    "♡ (˘▽˘>ԅ( ˘⌣˘)",
    "σ(≧ε≦σ) ♡",
    "(˘∀˘)/(μ‿μ) ❤",
    "Σ>―(〃°ω°〃)♡→",
    "(* ^ ω ^)",
    "(o^▽^o)",
    "ヽ(・∀・)ﾉ",
    "(o･ω･o)",
    "(^人^)",
    "( ´ ω ` )",
    "(´• ω •`)",
    "╰(▔∀▔)╯",
    "(✯◡✯)",
    "(⌒‿⌒)",
    "(*°▽°*)",
    "(´｡• ᵕ •｡`)",
    "ヽ(>∀<☆)ノ",
    "＼(￣▽￣)／",
    "(o˘◡˘o)",
    "(╯✧▽✧)╯",
    "( ‾́ ◡ ‾́ )",
    "(๑˘︶˘๑)",
    "(´･ᴗ･ ` )",
    "( ͡° ʖ̯ ͡°)",
    "( ఠ ͟ʖ ఠ)",
    "( ಥ ʖ̯ ಥ)",
    "(≖ ͜ʖ≖)",
    "ヘ(￣ω￣ヘ)",
    "(ﾉ≧∀≦)ﾉ",
    "└(￣-￣└))",
    "┌(＾＾)┘",
    "(^_^♪)",
    "(〜￣△￣)〜",
    "(｢• ω •)｢",
    "( ˘ ɜ˘) ♬♪♫",
    "( o˘◡˘o) ┌iii┐",
    "♨o(>_<)o♨",
    "( ・・)つ―{}@{}@{}-",
    "(*´з`)口ﾟ｡ﾟ口(・∀・ )",
    "( *^^)o∀*∀o(^^* )",
    "-●●●-ｃ(・・ )",
    "(ﾉ≧∀≦)ﾉ ‥…━━━★",
    "╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ",
    "(∩ᄑ_ᄑ)⊃━☆ﾟ*･｡*･:≡( ε:)",
    "OwO",
)

TOSS = (
    "Heads",
    "Tails",
)


DECIDE = ("Yes.", "No.", "Maybe.", "Who the hell cares?", "No one give a damn about it")

INSULT_STRINGS = [
    "`Owww ... Such a stupid idiot.`",
    "`Don't drink and type.`",
    "`Command not found. Just like your brain.`",
    "`Bot rule 544 section 9 prevents me from replying to stupid humans like you.`",
    "`Sorry, we do not sell brains.`",
    "`Believe me you are not normal.`",
    "`I bet your brain feels as good as new, seeing that you never use it.`",
    "`If I wanted to kill myself I'd climb your ego and jump to your IQ.`",
    "`You didn't evolve from apes, they evolved from you.`",
    "`What language are you speaking? Cause it sounds like bullshit.`",
    "`You are proof that evolution CAN go in reverse.`",
    "`I would ask you how old you are but I know you can't count that high.`",
    "`As an outsider, what do you think of the human race?`",
    "`Ordinarily people live and learn. You just live.`",
    "`Keep talking, someday you'll say something intelligent!`.......||I doubt it though||",
    "`Everyone has the right to be stupid but you are abusing the privilege.`",
    "`I'm sorry I hurt your feelings when I called you stupid. I thought you already knew that.`",
    "`You should try tasting cyanide.`",
    "`You should try sleeping forever.`",
    "`Pick up a gun and shoot yourself.`",
    "`Try bathing with Hydrochloric Acid instead of water.`",
    "`Go Green! Stop inhaling Oxygen.`",
    "`God was searching for you. You should leave to meet him.`",
    "`You should Volunteer for target in an firing range.`",
    "`Try playing catch and throw with RDX its fun.`",
    "`People like you are the reason we have middle fingers.`",
    "`When your mom dropped you off at the school, she got a ticket for littering.`",
    "`You’re so ugly that when you cry, the tears roll down the back of your head…just to avoid your face.`",
    "`If you’re talking behind my back then you’re in a perfect position to kiss my` ||A-S-S||!.",
    "`Awww! how cute.....me not you`",
    "`You are so ugly that if one direction sees you, they will change their direction to another...`",
    "`You left your brain to God go and take it...`",
    "`If you think you are an idiot..............then you are absolutely right...`",
]


BAN_GIFS = [
    "https://tenor.com/bqhVe.gif",
    "https://tenor.com/bsHe5.gif",
    "https://j.gifs.com/y5Pr8z.gif",
    "https://tenor.com/bfvQv.gif",
    "https://j.gifs.com/lO0lv6.gif",
    "https://tenor.com/bGMhb.gif",
    "https://tenor.com/bjZai.gif",
    "https://media.giphy.com/media/fe4dDMD2cAU5RfEaCU/giphy.gif",
    "https://tenor.com/bndta.gif",
    "https://tenor.com/bkyIr.gif",
    "https://media.giphy.com/media/UBqgQxKnUJqb8oZ2zc/giphy.gif",
    "https://media.giphy.com/media/tanIENriCOil3ndF3V/giphy.gif",
    "https://media.giphy.com/media/fwX4RUzdkdx9XUGow4/giphy.gif",
    "https://media.giphy.com/media/XVLfZCU6jDvMYqF1xS/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/CI4aCJUjJDJEj3Jgo4/giphy-downsized-large.gif",
    "https://media.giphy.com/media/0jcrQmPmyI5U532qL2/giphy.gif",
]

KICK_GIFS = [
    "https://tenor.com/bizBJ.gif",
    "https://tenor.com/bjPvj.gif",
    "https://tenor.com/bJMx3.gif",
    "https://tenor.com/bJCGL.gif",
    "https://tenor.com/bsIMJ.gif",
    "https://tenor.com/buURG.gif",
    "https://tenor.com/bNOj9.gif",
    "https://tenor.com/NfK8.gif",
    "https://tenor.com/ymZn.gif",
    "https://tenor.com/77Lu.gif",
    "https://tenor.com/bPD4I.gif",
    "https://tenor.com/bOGXo.gif",
    "https://tenor.com/bDLqs.gif",
    "https://media.giphy.com/media/u2LJ0n4lx6jF6/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/eDR7j2vjCFOUMJ9rT2/giphy.gif",
    "https://media.giphy.com/media/ERNKP5G7ihZNW6VW4Q/giphy.gif",
    "https://media.giphy.com/media/1r6xks2F0iHfbNvt4p/giphy.gif",
    "https://media.giphy.com/media/M7j1rkxm0X5z30Hyrs/giphy.gif",
    "https://media.giphy.com/media/rad9oJzU4hVafD8ZnT/giphy.gif",
    "https://media.giphy.com/media/TcliN5WDKBbnUQ15H3/giphy.gif",
    "https://media.giphy.com/media/y9pfUqY3uaT1MPXxYM/giphy.gif",
]


MUTE_GIFS = [
    "https://media.giphy.com/media/MpCxz9VLh6t8ceRb0r/giphy.gif",
    "https://media.giphy.com/media/HWl1atKEPAWcw/giphy.gif",
    "https://media.giphy.com/media/1xkynOSsb8eFpbEood/giphy.gif",
    "https://media.giphy.com/media/LmUAM5ImMNZd0nnkvn/giphy.gif",
    "https://media.giphy.com/media/JNlXHSSioDe7YGTC7D/giphy.gif",
    "https://media.giphy.com/media/t0iSe43jX8JH0Hb95a/giphy.gif",
    "https://media.giphy.com/media/P4CXV70NTC0umRI61S/giphy.gif",
    "https://media.giphy.com/media/Z0WPxDF7zpIHVPrYUN/giphy.gif",
    "https://media.giphy.com/media/gJS1pGTbXlSCWUe2pg/giphy.gif",
    "https://media.giphy.com/media/SIoetMN7j96O5perEV/giphy.gif",
    "https://media.giphy.com/media/PBZrH2uy9E5rPruuCX/giphy.gif",
    "https://media.giphy.com/media/Cew2qzlug9t3ACYrD5/giphy.gif",
    "https://media.giphy.com/media/PtIm7eUGKYIZbknqsO/giphy.gif",
    "https://media.giphy.com/media/EKbCY8OgdATSGBekxM/giphy.gif",
]

NOWYES = [
    """
YES          YES              YESYES
YESYES   YES         YES          YES
YES  YES YES       YES               YES
YES    YESYES     YES                YES
YES      YESYE         YES         YES
YES          YES               YESYES
          """
]

YESWNO = [
    """
NO       NO   NONONO            NONO
 NO     NO    NO                      NO         NO
   NONO       NO                       NO
      NO           NONO                      NO
      NO           NO                 NO          NO
      NO           NO                    NO        NO
      NO           NONONO           NONO
"""
]

StartPic = [
"https://graph.org/file/c5d90358cff42932a850f.jpg",
"https://graph.org/file/b83c674087f50f3987be5.jpg",
"https://graph.org/file/6e4fea45ad353217d4bab.jpg",
"https://graph.org/file/a04bf7325e8b146bd47b0.jpg",
"https://graph.org/file/9bbc7a14aec53b0243545.jpg",
"https://graph.org/file/d7ba94cdbdf08b16a0f69.jpg",
"https://graph.org/file/18c32dd3c064e1931f64e.jpg",
"https://graph.org/file/985e0e1e8e80b20b77a79.jpg",
"https://graph.org/file/4fdd27402523bcfa0b30f.jpg",
"https://graph.org/file/b71f28bd156069dceaf34.jpg",
"https://graph.org/file/c3e390b4b5e5bd152f190.jpg",
"https://graph.org/file/5c288d06fccc3a52cc088.jpg",
"https://graph.org/file/f77195778afd69c6dfccd.jpg",
"https://graph.org/file/e9c3f87d495f85cdd0a10.jpg",
"https://graph.org/file/b715aa82f095f02c675ec.jpg",
"https://graph.org/file/5c288d06fccc3a52cc088.jpg"
]


birthday_wish =  [
    "Wishing you a happy birthday filled with love and joy.",
    "Hope your birthday is as wonderful as you are.",
    "Happy birthday to someone who deserves an exceptional day.",
    "May your birthday be full of surprises and delight.",
    "Wishing you a year filled with new adventures and accomplishments.",
    "May your birthday be as sweet as cake and as joyful as the celebration.",
    "Here's to a fabulous birthday and a year filled with blessings.",
    "Sending you lots of love and warm wishes on your special day.",
    "May your birthday be a time for reflection, relaxation, and joy.",
    "Cheers to another year of making unforgettable memories!",
    "May your birthday be filled with laughter, love, and good times.",
    "Wishing you a birthday that's just as amazing as you are.",
    "Here's to a year filled with love, happiness, and success.",
    "May your birthday be filled with all the love and blessings you deserve.",
    "Sending you warm wishes for a joyful and memorable birthday.",
    "Wishing you a birthday that's as wonderful as you are.",
    "May your birthday be a time to celebrate all the amazing things you've accomplished.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you lots of love, hugs, and birthday wishes.",
    "May your birthday be full of sunshine, laughter, and good times.",
    "Wishing you a year filled with happiness, success, and love.",
    "Here's to a fantastic birthday and an even better year ahead!",
    "May your birthday be a day filled with joy, love, and celebration.",
    "Sending you lots of love and warm wishes on your special day.",
    "Wishing you a birthday that's as bright and beautiful as you are.",
    "May your birthday be full of love, laughter, and happiness.",
    "Here's to a year filled with exciting adventures and new opportunities.",
    "Wishing you a birthday that's just as amazing as you are.",
    "May your birthday be a time to reflect on all the wonderful things in your life.",
    "Sending you lots of love, hugs, and birthday wishes from afar.",
    "Wishing you a year filled with love, laughter, and all your heart desires.",
    "May your birthday be a time to relax, unwind, and enjoy the company of loved ones.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you warm wishes for a wonderful and unforgettable birthday.",
    "Wishing you a birthday that's as special and unique as you are.",
    "May your birthday be a time to cherish all the special moments and memories you've created.",
    "Here's to a year filled with joy, laughter, and happiness.",
    "Wishing you a birthday that's just as amazing as you are.",
    "May your birthday be a time to celebrate your wonderful achievements and accomplishments.",
    "Sending you lots of love, hugs, and birthday wishes to make your day extra special.",
    "Wishing you a year filled with love, happiness, and all your heart's desires.",
    "May your birthday be a time to create new memories and cherish old ones.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you warm wishes for a fabulous and unforgettable birthday.",
    "Wishing you a birthday that's full of love, laughter, and happiness.",
    "May your birthday be a time to appreciate all the wonderful people in your life.",
    "Wishing you a birthday as amazing as you are, filled with joy and memories to last a lifetime.",
    "May your birthday be full of laughter and love, and your year be full of happiness and success.",
    "Happy birthday to someone who makes the world a better place, may all your wishes come true.",
    "Sending you warm birthday wishes and virtual hugs, can't wait to celebrate in person!",
    "May your birthday be as special as you are, surrounded by all the people who love you the most.",
    "Wishing you a day filled with laughter and a year filled with new adventures and opportunities.",
    "Happy birthday to someone who's always there to brighten up my day, may your day be as bright as you are.",
    "Here's to a birthday that's just as awesome as you are, and a year filled with love and happiness.",
    "May your birthday be a time to reflect on all the wonderful memories you've made, and look forward to new ones.",
    "Wishing you a birthday that's full of surprises and excitement and a year filled with new beginnings.",
    "Happy birthday to my favourite person in the world, may your day be as special as you are to me.",
    "Sending you the biggest birthday hugs and all my love, may your day be filled with joy and celebration.",
    "May your birthday be a time to celebrate all your accomplishments and be proud of all you've achieved.",
    "Wishing you a birthday that's as bright and beautiful as you are, filled with love and laughter.",
    "Happy birthday to a true gem, may your day be filled with joy, laughter, and all the things you love.",
    "Here's to a birthday that's full of happiness, excitement, and all the people who make your life special.",
    "May your birthday be a time to let loose and have fun, and your year be filled with growth and success.",
    "Wishing you a birthday that's full of all the things you love and a year that's even better than the last.",
    "Happy birthday to someone who makes my life brighter, may your day be as amazing as you are.",
    "Sending you lots of love and virtual hugs on your special day, may your year be filled with blessings.",
    "May your birthday be a time to cherish all the people who make your life special, and celebrate the person you've become.",
    "Wishing you a birthday that's as unique and wonderful as you are, filled with love and laughter.",
    "Happy birthday to someone who's always been there for me, may your day be filled with joy and celebration.",
    "Here's to a birthday that's full of love, happiness, and all the things that bring you the most joy.",
    "May your birthday be a time to reflect on all the amazing things you've accomplished, and look forward to all that's to come.",
    "Wishing you a birthday that's full of surprises, happiness, and all the things that make you feel alive.",
    "Happy birthday to someone who brings a smile to my face every day, may your day be as wonderful as you are.",
    "Sending you all my love and warmest wishes on your special day, may your year be filled with love and happiness.",
    "May your birthday be a time to appreciate all the people who make your life special, and cherish all the memories you've created.",
    "Wishing you a birthday that's as beautiful as you are, filled with joy and celebration.",]
GDNIGHT = [
    "`പിടിക്ക് സൈതനെ ഒരു Good night`",
    "`ഇന്ന് രാത്രി ഉറങ്ങുബോൾ കൊതുക് കടിക്കില്ല Bcoz…My GOOD NIGHT Will take care of U.But.ചിലപ്പോ ഉറുമ്പ് കടിച്ചേക്കാം .!Bcoz.I Wish you a SWEET SWEET DREAM.!`",
    "`നല്ല നിലാവുള്ള രാത്രി ,സുഖ സീതളമായ കാറ്റ് ,നിദ്ര   way Good night. sweet Dreams`",
    "`ഒരൊറ്റ ഉറക്കം മതി നേരം പുലരാൻ .ദേ പോയി ദാ വന്നു ശുഭ നിദ്ര `",
    "`നല്ല നിലാവുള്ള രാത്രി ,സുഖ സീതളമായ കാറ്റ് ,നിദ്ര devi മിഴികളെ പുണരുന്നു ,എങ്കിൽ ആരെ നോക്ക് ഇരിക്കുവാ പോയി കിടന്നു ഉറങ്ങടാ `",
    "`പക്ഷികൾ ഉറങ്ങി സൂര്യനും ഉറങ്ങി കാറ്റും ഉറങ്ങി ,നീ മാത്രം മൈ എന്തെ ഉറങ്ങിയില്ല .Ooh!ഞാൻ മറന്നു എന്റെ GoodNightകാത്തിരിക്കുവാനല്ലേ ..GoOd NiGhT & SwEeT DreaMs`",
    "`സ്വപ്നങ്ങളുടെഅത്ഭുതലോകവുമായി ഇതാ ഒരു രാത്രി കൂടി വരവായി.മനോഹര സ്വപ്നങ്ങളും, ആ സ്വപ്‌നങ്ങൾ യാഥാർഥ്യമാക്കാനുള്ള ഊർജവുമായി നാളെ വീണ്ടും ഉണരാം. ഗുഡ് നൈറ്റ്.`",
    "`ജീവിതം ഒന്നേയുള്ളു. അത് തോൽവി സമ്മതിച്ചു ഉരുകി തീർക്കാനുള്ളതല്ല. പൊരുതി നേടാനുള്ളതാണ്. പൊരുതി നേടാനുള്ള കരുത്തുമായി നാളെ വീണ്ടു ഉണരാം.ശുഭ രാത്രി.`",
    "`മനസ്സിലുള്ള എല്ലാ സ്വപ്നങ്ങളും ആഗ്രഹങ്ങളും പ്രതീക്ഷകളും പൂവണിയുന്ന ഒരു നല്ല ദിവസമാവട്ടെ നാളെയെന്നു ആശംസിയ്ക്കുന്നു. ഗുഡ് നൈറ്റ്.`",
    "`നിങ്ങളുടെ വിജയത്തിലേയ്ക്കും പരാജയത്തിലേയ്ക്കും ഉള്ള ദൂരത്തിന്റെ പേര് ഒന്നാണ്…മനസ്സ്.. മനസ്സിനെ ജയിച്ചാൽ പിന്നെ ഒന്നിനും നിങ്ങളെ തോല്പിയ്ക്ക്യനാവില്ല `",
    "`രാത്രികൾ പകലിന്റെ സ്വപ്നങ്ങളാണ്. ഒരു പാട് പ്രതീക്ഷകളുമായി ഉറങ്ങുന്ന സ്വപ്‌നങ്ങൾ. ഗുഡ് നൈറ്റ് `",
    "`സ്വപ്നങ്ങളാണ് വിജയത്തിലേയ്ക്കയുള്ള ആദ്യ ചവിട്ടു പാടി. സ്വപ്‌നങ്ങൾ കാണുക. അവ യാഥാർഥ്യമാക്കാൻ പ്രയത്നിയ്ക്കുക. പുതിയൊരു ലോകം നിങ്ങള്ക്ക് മുന്നിൽ വാതിൽ തുറക്കും. ഗുഡ് നൈറ്റ്.`",
    "`നിന്റെ നെഞ്ചിടിപ്പിന്റെ താളമാവാൻ,നിന്റെ നിശ്വാസമാവാൻ, നിന്റെ പ്രതീക്ഷകളാവാൻ, നിന്റെ സ്വപ്നങ്ങളാവാൻ, നിന്നിലെ നീയാവാൻ എന്നെ അനുവദിയ്ക്കയു. ശുഭ രാത്രി `",
    "`നന്ദി, എനിയ്ക്കു സ്വപ്‌നങ്ങൾ തന്നതിന്, ജീവിതത്തിനു നിറങ്ങൾ തന്നതിനു, പുഞ്ചിരിത്തന്നതിനു, അതിലെല്ലാം ഉപരി എനിയ്ക്കു നിന്നെത്തന്നെ തന്നത്തിനു. ഗുഡ് നൈറ്റ്.`",
    "`കൂരിരുട്ടുള്ള രാത്രികൾക്കു ശേഷമാണ് നിറമുള്ള പകലുകൾ ഉണ്ടാകുന്നതു. ഈ കൂരിരുട്ടിനെ ഭയക്കേണ്ടതില്ല, നിറമാർന്ന ഒരു പ്രഭാതം നിന്നെ കാത്തിരിപ്പുണ്ട്. പ്രയത്നിയ്ക്കയു. ഗുഡ് നൈറ്റ്.`",
    "`നമ്മുടെ സ്വപ്നൾക്കു കടിഞ്ഞാണിടുന്നത് നമ്മൾ തന്നെയാണ്. നിറമുള്ള സ്വപ്‌നങ്ങൾ കാണാൻ മനസ്സിനെ അനുവദിയ്ക്കാം. ആ സ്വപ്നങ്ങളെ സത്യമാക്കാൻ നമുക്കു പ്രയത്നിയ്ക്ക്യം. ഗുഡ് നൈറ്റ്.`",
    "`നിന്റെ പാട്ടായി, കവിതയായി, നിഴലായി, സൗഹൃദമായി, പ്രണയമായി ഞാനെന്നും കൂടെയുണ്ടാവും. എന്നും എന്നെന്നും. ഗുഡ് നൈറ്റ് മൈ ലവ്.`",
    "`ഒരിയ്ക്കലും വരില്ലെന്നറിഞ്ഞിട്ടും നിന്റെ കാലൊച്ചയ്ക്കയായി ഞാൻ കാതോർക്കുന്നു, നിന്റെ മൃദുസ്പർശത്തിനായി ഹൃദയം തേങ്ങുന്നു. നീ വരുന്നതും കാത്തു എന്നും ഞാൻ ഈ പുഴയോരത്തുണ്ടാവും. ഗുഡ് നൈറ്റ്.`",
    "`പ്രതീക്ഷകളും സ്വപ്നങ്ങളുമാണ് മനുഷ്യനെ മുന്നോട്ടുനയിയ്ക്കുന്നതു. എന്നും നിറമുള്ള സ്വപ്നങ്ങൾ കൂടെയുണ്ടാവട്ടെ എന്ന് പ്രാർത്ഥിച്ചുകൊണ്ട്, ഗുഡ് നൈറ്റ്.`",
    "`ഇന്നത്തെ സ്വപ്‌നങ്ങൾ നാളെയെ കുറിച്ചുള്ള പ്രതീക്ഷകളാകട്ടെ. നാളെയുടെ പ്രതീക്ഷകൾ നിങ്ങളുടെ ജീവിത വിജയത്തിന്റെ നാഴികക്കല്ലുകളാകട്ടെ. ഗുഡ് നൈറ്റ്.`",
    "`മറ്റുള്ളവർ നിങ്ങള്ക്ക് നേരെ എറിയുന്ന കല്ലുകൾ നിങ്ങളുടെ ചവിട്ടുപടികളാക്കി മാറ്റുക. ഗുഡ് നൈറ്റ്.`",
    "`ഈ ജനലഴികളിലൂടെ രാത്രിയുടെ വിദൂരതയിലേക്ക് നോക്കിയിരിയ്ക്കുമ്പോളും, മനസ്സിൽ മായാതെ നിന്റെ ഓർമ്മകൾ മാത്രമാണ്. എന്നെ ജീവിയ്ക്ക്യാൻ പ്രേരിപ്പിയ്ക്കയുന്ന എന്റെ പ്രിയ സ്വപ്നമേ, നിനക്ക് ശുഭ രാത്രി നേരുന്നു.`",
    "`പ്രണയം വാടിയതിനെ വളർത്താനും, മരിച്ചതിനെ ജീവിപ്പിയ്ക്കാനും കഴിവുള്ള ഔഷധമാണ്. ശുഭ രാത്രി.`",
    "`അകലെയാണെങ്കിലും എന്നും എന്റെ നെഞ്ചിൽ നീയുണ്ടുനിന്റെ ശ്വാസത്തിന്റെ താളമുണ്ട്നിന്റെ ശബ്ദത്തിന്റെ സംഗീതമുണ്ടുനിന്റെ ഓർമ്മകളുമായി ഞാനിന്നു സുഗമായുറങ്ങുന്നുനാളെയൊരുനാൾ നാം വീണ്ടുംകണ്ടുമുട്ടും.ശുഭ രാത്രി.`"
    "`സ്വപ്നങ്ങള്ക്ക് ജീവനില്ല പക്ഷേ പലരും ജീവിക്കുന്നത് സ്വപ്നങ്ങള്ക്ക് വേണ്ടി ആണെന്ന് മാത്രംശുഭ രാത്രി`",
    "`എന്റെ ഒപ്പം നടക്കാനാണ് ഇഷ്ടംഎന്ന് ആരും പറഞ്ഞിട്ടില്ല.. എന്നാൽപറയാതെ കൂടെ നടന്നത്...ആകാശത്തിലെ ചന്ദ്രൻ മാത്രം:ഗുഡ് നൈറ്റ് `",
    "`ചായം പോയ  സന്ധ്യയിൽ നീറും പൊൻചിരാതുകൾ .... ഒര്മതൻ ചില്ലയിൽ കൂടണഞ്ഞ മൗനങ്ങൾ ........ശുഭരാത്രി.`",
    "`നമ്മളുറങ്ങുമ്പോൾ വരാൻ..എത്രയെത്ര സ്വപ്നങ്ങളായിരിക്കാം ഉണർന്നിരിക്കുന്നുണ്ടാവുക..💥ശുഭ രാത്രി💥 `",
    "`ഇന്ന് നീ മറക്കാൻ ശ്രമിച്ചതെല്ലാംനാളെ നിനക്ക് ഓർക്കാൻ കഴിഞ്ഞേക്കാം. പക്ഷേ ഇന്ന് നിനക്ക് നഷ്ടമായതൊന്നും നാളെ തിരിച്ച് കിട്ടീ എന്ന് വരില്ല......ഗുഡ് നൈറ്റ് `",
]

GDMORNING = [
    "`എന്നെ എന്തിനാ ഇത്രയും പരീക്ഷിക്കുന്നത് ദൈവമേ എന്ന് ചിന്തിക്കുന്നതിലും നല്ലതല്ലേ എന്നെ ഇത്രയല്ലേ പരീക്ഷിച്ചത് ദൈവമേ ഗുഡ് മോർണിംഗ്`",
    "`നീ മരിച്ചാലും ഞാൻ നിന്നെ സ്നേഹിക്കും...... ഞാൻ മരിച്ചാലും ആ സ്നേഹം നില നിൽക്കും.... ശുഭദിനം.... കൂട്ടുക്കാരെ`",
    "`കഴിഞ്ഞു പോയ ദിവസത്തെ ഓർത്തു കരയരുത് ...കാരണം ......നാളത്തെ പുലരി ഇന്നത്തേക്കാൾ മനോഹരമായിരിക്കും ....സുപ്രഭാതം`",
    "`വിധിയെ... നീയും, അറിയണം ഒന്നുമില്ലാത്തവനും ഇവിടെ ഒരായിരം സ്വപ്നങ്ങൾ നെയ്തു കാത്തിരിക്കുന്നുണ്ടെന്ന്.`",
    "`അസ്തമയങ്ങളെ ഞാൻ ശ്രദ്ധിക്കാറില്ല.. !!! നാളെയുടെ ഉദയങ്ങലിലാണ് എനിക്ക് പ്രതിക്ഷ Good morning!`",
    "`ഇന്നലെകൾ ഓർമ്മകളായ് നാളെകൾ പ്രതീക്ഷകളുമാണ് ജീവിതമെന്നത് ഇന്നാണ് ശുഭദിനം`",
    "`എനിക്ക് ചിലരെ സ്നേഹിക്കാൻ ചില പ്രതേക കാരണങ്ങൾ മതി... അവർക്കെങ്ങനെ വെറുക്കാൻ നൂറോളംകാരണങ്ങൾ ഉണ്ടുതാനും ...ഗുഡ് മോർണിംഗ്`",
    "`സത്യത്തിന്റെയും ☺ നീതിയുടേയും വിനയത്തിന്റെയും പ്രതീകമായ..ഞാന്‍ എണീറ്റു ഗുഡ്മോർണിംഗ് ☕`",
    "`ജീവിതം അത് മനോഹരമാണ്. കഴിഞ്ഞുപോകുന്ന ഒരു ദിവസം, ഒരു മണിക്കൂർ, അല്ലെങ്കിൽ ഒരു മിനുട്ട് ഈ ജീവിതകാലം മുഴുവൻ നമുക്ക് തിരിച്ചു കിട്ടില്ല. കലഹവും ദേഷ്യവുമെല്ലാം ഒഴിവാക്കിയേക്കുക. എല്ലാവരോടും സ്നേഹത്തോടെ, വിനയത്തോടെ സമാധാനത്തോടെ പെരുമാറുക ശുഭദിനം`",
    "`മറ്റുള്ളവരുടെ അഭിപ്രായമനുസരിച്ച് തീരുമാനങ്ങള്‍ എപ്പോഴും മാറ്റിമറിക്കരുത് നന്മയും തിന്മയും തിരിച്ചറിഞ്ഞ് അതിനെതിരെ ഉറച്ച തീരുമാനങ്ങൾ എടുക്കുന്നവന് വിജയം സുനിശ്ചിതമായിരിക്കും ശുഭദിനം`",
    "`നല്ല കാര്യങ്ങൾ ചെയ്തുകൊണ്ടിരിക്കുക... ആരെയും ബോധ്യപ്പടുത്താൻ ശ്രമിക്കാതിരിക്കുക..ആളുകൾ ഒരിക്കലും നമ്മളിൽ സന്തുഷ്ടരാവുകയില്ല... ആരിൽ നിന്നും ഒരു നന്ദി വാക്കുപോലും പ്രതീക്ഷിക്കേണ്ടതുമില്ല... ഫലം ഇച്ഛിക്കാതെ കർമ്മം ചെയ്യുക..... വിജയം ഉറപ്പായും നമ്മെ തേടിയത്തും..ശുഭദിനം`",
    "`ജീവിത യാത്ര വളരെ കുറഞ്ഞ ദൂരം മാത്രമേ ഒളളൂ. അതിനിടക്കെന്തിന് ഈ പകയും വിദ്ദേഷവും തമ്മിൽ തല്ലും പിണക്കവുമെല്ലാം. സുപ്രഭാതം`",
    "`ജീവിത യാത്ര വളരെ കുറഞ്ഞ ദൂരം മാത്രമേ ഒളളൂ. അതിനിടക്കെന്തിന് ഈ പകയും വിദ്ദേഷവും തമ്മിൽ തല്ലും പിണക്കവുമെല്ലാം. സുപ്രഭാതം`",
    "`തേനൂറും വാക്കിലല്ല മധുവൂറും പ്രവർത്തിയിലാകണം ഹൃദയങ്ങൾ കീഴടക്കേണ്ടത്... ശുഭദിനം`",
    "`ഒരു നാൾ സൂര്യൻ ഉദിക്കാൻ മടിച്ചാൽ തീരാവുന്നതേയുള്ളു മനുഷ്യന്റെ ഈ തിരക്ക് .സുപ്രഭാതം`",
    "`മഴയുടെ നേർത്ത രാഗം പോലെ പെയ്തു തീർന്നിട്ടും ബാക്കി നിൽക്കുന്ന മേഘങ്ങൾ പോലെ ചില ഓർമ്മകൾ എന്നും കൂടെയുണ്ടാവും.... വീണ്ടും വീണ്ടും ഓർത്തെടുക്കാൻ... ആ ഓർമ്മകളിലൂടെ ഇന്നത്തെ പുലരി നേരുന്നു.... ശുഭദിനം`",
    "`മറക്കാൻ കഴിയാത്ത ഓർമകൾക്ക് കൂടുകൂട്ടാൻ ഹൃദയം സമ്മദിക്കുമായിരുന്നില്ലെങ്കിൽ ജീവിതം സുന്ദരമാകുമായിരുന്നേനെ good morning`",
    "`സ്വന്തം കഴിവ് തിരിച്ചറിയാൻ കഴിയാത്ത മനുഷ്യന് എവിടെ ചെന്നാലും പരാജയം ആയിരിക്കും ഗുഡ്‌ മോർണിംഗ് ഫ്രണ്ട്‌സ്`",
    "`ചിന്താപ്രഭാതം സ്വഭാവമാണ് സൗന്ദര്യത്തേക്കാള്‍ മികച്ചത്. മനുഷ്യത്വമാണ് സമ്പത്തിനേക്കാള്‍ മികച്ചത്. എന്നാൽ ബന്ധങ്ങൾ സൂക്ഷിക്കുന്നതിനേക്കാൾ മികച്ചതായി ഒന്നുമില്ല. സുപ്രഭാതം`",
    "`ആത്മാർത്ഥതയില്ലാത്ത സൗഹൃദം വന്യമൃഗങ്ങളെക്കാൾ ഭയാനകർമാണ്.വന്യമൃഗത്തിന് നിങ്ങളുടെ ശരീരത്തെ ഹനിക്കാം. എന്നാൽ വക്രബുദ്ധി യുള്ള സുഹൃത്ത് ഹനിക്കുന്നത് നിങ്ങളുടെ ആത്മാവിനെയും ആത്മാർത്ഥതയെയും ചൂഷണം ചെയ്യും ഓർക്കുക.. ഐശ്വര്യപൂർണ്ണമായ നല്ലൊരു ദിവസം ആശംസിക്കുന്നു... സുപ്രഭാതം`",
    "`അകലം ഒരിക്കലും സ്നേഹബന്ധങ്ങളിൽ വിള്ളൽ വീഴ്ത്തുന്നില്ല ... സ്നേഹബന്ധങ്ങളിൽ വിള്ളൽ വീഴ്ത്തുന്നത് വിശ്വാസക്കുറവും സംശയവുമാണ് ... സുപ്രഭാതം`",
    "`മനസ് വിതുമ്പുന്ന സമയത്തും ചിരിക്കാൻ കഴിയുന്നത് ഒരു ഭാഗ്യമാണ്, ഒരു വരദാനമാണ്. ഒന്നും സ്വന്തമായി ഇല്ലാത്തവർക്ക് ദൈവത്തിന്റെ സമ്മാനമാണ് അങ്ങനെ ചിരിക്കാനുള്ള കഴിവ് പുഞ്ചിരി കൊണ്ട് പൂമാല തീർക്കാൻ കഴിയട്ടെ ഇന്നത്തെ ഈ ദിവസം ശുഭദിനം`",
    "`സ്‌നേഹം നെല്ല് പോലെയാണ്, വിതച്ചാലാണ് മുളയ്ക്കുക. അഹങ്കാരം പുല്ല് പോലെയും, ഒന്നും ചെയ്യാതെ തന്നെ അത് മുളയ്ക്കും. സുപ്രഭാതം`",
    "`ഒരിക്കലും വിട്ടുപോകാൻ കഴിയില്ലെന്ന് തോന്നുന്ന എല്ലാത്തിനോടും ഒറ്റയടിക്ക് വിടപറഞ്ഞു നോക്കണം. മുന്നോട്ട് ജീവിക്കാൻ വല്ലാത്ത ഒരു ധൈര്യം കിട്ടും.. നല്ലൊരു ഭിവസം നേരുന്നു`",
    "`ഇന്നലെകളെ ഓർത്തുംകൊണ്ട് ജീവിക്കരുത്ത്.നാളെയെക്കുറിച്ച് സ്വപ്നങ്ങൾ കാണുകയും അരുത്.ഇന്നിൽ മാത്രം നിങ്ങളുടെ സർവ്വ ശൃദ്ധയും കേന്ദ്രീകരിക്കുക`",
    "`ചിന്തകൾക്ക് ഉണർവേകുമ്പോൾ മാത്രമേ മനുഷ്യനു സത്യത്തിന്റെ പാത കണ്ടെത്താൻ കഴിയുകയുള്ളു ശുഭദിനം`",
    "`ഒരു ലക്ഷ്യം നിന്‍റെ മുന്നിലുണ്ടോ.. എങ്കിൽ ആ ലക്ഷ്യത്തിലേക്കുള്ള വഴികളിലെ മുള്ളുകളും കല്ലുകളും നിനക്കൊരു പ്രശ്നമാകില്ല.... ശുഭദിനം`",
    "`വളർന്ന് വരുമ്പോൾ പെൻസിൽ മാറ്റി പേന വച്ചുതരുന്നത് എന്തിനെന്നറിയോ: ഇനിയുള്ള ലൈഫിൽ തെറ്റുകൾ പറ്റിയാൽ മായ്ക്കാൻ എളുപ്പമല്ല എന്ന ബോധം ഉണ്ടാവാൻ .... സുപ്രഭാതം`",
    "`നാളെയുടെ സ്വപ്‌നങ്ങൾ എന്നെ ഉറങ്ങാൻ കൊതിപ്പിക്കുന്നു . ഇന്നലെയുടെ ഓർമകൾ എന്റെ ഉറക്കം കെടുത്തുന്നു . ശുഭദിനം`",
    "`ചിലർക്കു നമ്മളെ മനസ്സിലാക്കാൻ കഴയില്ല ... മനസ്സിലാക്കിയവർ നമ്മോടൊപ്പം ഉണ്ടാവുകയുമില്ല ശുഭദിനം ☺`",
    "`വേഗത കൂടിയ ഈ യാത്രാവണ്ടിയിൽ ഇന്ന് അതിജീവിച്ചവർ നാളെയ്ക്കുള്ള പ്രതീക്ഷയിലാണ് ....നാളെയും അതിജീവിക്കുന്നവർ പ്രതീക്ഷയുടെ വിജയമാണ് ..ശുഭദിനം`",
    "`ആരുടെയും കൗതുകമാവാതിരിക്കുക. എല്ലാ കൗതുകങ്ങൾക്കും ഒരു എക്സ്പയറി ഡേറ്റുണ്ട്. ശുഭ ദിനം`",
    "`മനസ്സിന്റെ കണ്ണാടിയായി മാറുന്ന ഒരു സുഹൃത്ത് ബന്ധം ഈ ദിവസം ഉണ്ടാവാട്ടെ എന്നു ആശംസിച്ചു കൊണ്ട് ശുഭദിനം`",
    "`കാലതാമസം, ഓർമ്മക്കുറവ്, അലസത, ആവിശ്യത്തിലധികം ഉറക്കം ഈ നാലും ജീവിത പുരോഗതിക്ക് വിഘ്നങ്ങളാകുന്നു..... ശുഭ ദിനം ശുഭ ചിന്തകൾ`",
    "`മറവി ഒരു അനുഗ്രഹമായിരിക്കാം ...പക്ഷേ ഓർക്കാതിരിക്കുന്നതു ബോധപൂർവമായ ഒരു തെറ്റാണ് .. ശുഭദിനം `",
]

MSLAP_TEMPLATES = (
    "{user2}വിനെ {user1} ഭിത്തിയിൽ ചേർത്ത് നിർത്തി കണ്ണിൽ മുളക് തേച്ചു😵.",
    "{user2} എന്ന ആളുടെ വായിൽ {user1} തുപ്പി ഇട്ടു.😳",
    "{user2} എന്ന ആളെ കൊണ്ട് {user1} ഓലേക്കപുണ്ണാക്ക് തീറ്റിച്ചു.🤢",
    "{user2} എന്ന ആളെ മുതല കുളത്തിൽ തള്ളി ഇട്ടു",
    "{user2}ക്ക് സയനൈഡ് കൊടുത്തു",
    "{user2} എന്ന ആളെ തീയിൽ ഇട്ടു.",
    "{user2} എന്ന ആൾ {user1} ആയിട്ടു അടി കൂടിയപ്പോ കരിഞ്ഞു പോയി.",
    "{user2} തലയിൽ ഇടി വെട്ടി",
    "{user2} എന്ന ആളുടെ വായിൽ {user1} ഉപ്പിട്ടു.",
    "{user2} എന്ന ആളെ നാട്ടുകാർ തല്ലി കൊന്നു",
    "{user2} പട്ടിണി കിടന്നു മരിച്ചുപോയി",
    "{user2} ജീവിച്ചിരിപ്പുണ്ടോ ഇതൊക്കെ",
    "{user2} എന്ന ആളെ {user1} പേടിപ്പിച്ചു കൊന്നു.",
    "{user2} എന്ന ആൾ വല്യ വിറ്റാണ് കേട്ടോ....",
    "{user2} താനൊസ് സ്നാപ്പ് ചെയ്തപ്പോ മഞ്ഞു പോയി",
    "{user2} എന്ന ആളുടെ കാലിന്റെ ഇടയിൽ ബോംബ് ഇട്ടു പൊട്ടിച്ചു.",
    "{user2} എന്ന ആളുടെ വായിൽ സൂപ്പർ ഗ്ലു ഇട്ടു....",
    "{user2} നെ ലോകത്തിൽ ഏറ്റവും വലിയ ദുരന്തങ്ങൾ ആയിട്ടു പ്രഖ്യാപിച്ചു.",
    "{user2} ക്യാഷ് അങ്ങോട്ടു കൊടുത് വിറ്റു",
    "{user2} ന് {user1} പിണ്ണാക്ക് വാങ്ങി കൊടുത്തു.",
    "{user2}ന്റെ തലയിൽ {user1} ചെണ്ട കൊട്ടി.",
    "{user2}ന്റെ പ്രധാന ഭാഗത്ത്‌ പാൻ വെച്ചടിച്ചു",
    "{user2} ഒരു വികൃത ശരീരം ഉള്ള സോമ്പി ആണ് എനിക് ഒന്നും ചെയ്യാൻ പറ്റില്ല.",
    "{user2} ഒരു മണ്ടൻ ആയതു കൊണ്ട് വെറുതെ വിട്ടിരിക്കുന്നു.",
    "{user2} ന്റെ തലയിൽ ഇഷ്ടിക തള്ളി ഇട്ടു.",
    "{user2} ഒരു കാറ്റത് പറന്നു പോയി.",
    "{user2} ഒരു ബോംബ് എടുത്ത് തിന്നു",
    "{user2} നടന്നു പോയപ്പോൾ കാക്കക്ക് തലയിൽ അപ്പി ഇടാൻ അവസരം കൊടുത്തു",
    "{user2} was terminated by {user1}.",
    "{user2} ഇരുന്നപ്പോൾ കൊന്നു കളഞ്ഞു.",
    "{user2} എന്ന ആളുടെ കണ്ണിൽ പെൻസിൽ എടുത്ത് കുത്തി.",
    "{user2} ന്റെ  ഫോൺ എടുത്ത് വെള്ളത്തിൽ ഇട്ടു.",
    "{user1} എന്ന ആളുടെ ദേഹത്തു കൂടെ {user2} റോഡ് റോളർ കേറ്റി ഇറക്കി.",
    "{user2} ഒരു കല്ലെടുത്ത് മുകളിലോട്ടു എറിഞ്ഞു അത് വന്നു സ്വന്തം തലയിൽ വീണു മരിച്ചു പോയി",
    "{user1} ആരും അറിയാതെ {user2}ന്റെ കാലിൽ ടൈം ബോംബ് വെച്ചു കെട്ടി.",
    "{user1} ഒരു കല്ലെടുത്ത് {user2} എന്ന ആളുടെ മർമ്മം നോക്കി എറിഞ്ഞു.",
    "{user1} put {user2} in check-mate.",
    "{user1} കോടാലി എടുത്ത് {user2} വിന്റെ വായിൽ തിരുകി വെച്ചു.",
    "{user1} {user2}നെ വാരികുഴിയിൽ തള്ളി ഇട്ടു.",
    "{user1} മീൻ ചട്ടി എടുത്ത {user2} ന്റെ തലക്കടിച്ചു",
    "{user2} തുണി ഇല്ലാതെ റോഡിൽ കൂടി ഓടി.",
    "{user2} ന്റെ ഫോണിൽ നിന്നും {user1} പ്രധാന പെട്ട ഫയൽ എല്ലാം തന്നെ ഡിലീറ്റ് ചെയ്തു.",
    "{user1}  {user2}ന്റെ പല്ലെല്ലാം അടിച്ചു താഴെ ഇട്ടു.",
    "{user2} എന്ന ആളുടെ പാന്റ് നാടു റോഡിൽ വെച്ചു ഊരി പോയി.",
    "{user1} അലക്കാത്ത തുണി എടുത്ത് {user2}ന്റെ വായിൽ കുത്തി കേറ്റി.",
    "{user2} കൂടുതൽ തൊള്ള തുറന്നാൽ അടിച്ചു അണ്ണാക്കിൽ തരും എന്നു പറയാൻ പറഞ്ഞു {user1}.",
    "{user2} എന്ന ആളുടെ ബുദ്ധി, ശൂന്യം ആണ്.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} പെട്രോൾ കുടിച്ചു ചിരിച്ചു",
    "{user1} {user2}നെ ബാറ്റ് വെച്ച് {hits}.",
    "{user1} {user2}നെ കൊക്കയിൽ ഇട്ടു.",
    "{user1} {user2} എന്ന ആളെ പലക എടുത്ത് {hits}",    
    "{user1} {user2} എന്ന ആളുടെ തലയിൽ {hits}.",
    "{user1} {user2} എന്ന ആളുടെ വായിൽ ലാവാ ഒഴിച്ചു.",
    "{user1} വലിയ ഒരു പാറ എടുത്ത് {user2} തലയിൽ ഇട്ടു .",
    "{user1} {user2}ന്റെ തലയിൽ വലിയ പാൻ കാക്ക എടുത്ത് {hits}!.",
    "*{user2} എന്ന ആളെ തല കീഴായി തൂക്കി ഇട്ട് അടിച്ചു*.",
    "*{user2} എന്ന ആളുടെ പിന്നാമ്പുറത്ത് ചട്ടുകം വെച്ചു പൊള്ളിച്ചു*.",
    "*{user2} നെ ഉന്തി ഇട്ടു*.",
    "*{user2} നെ {user1} തല്ലിയിട്ടു ഓടി*.",
    "*{user2} ചെരുപ്പ് ഇട്ടു നടന്നതിന് നാട്ടുകാർ ഓടിച്ചിട്ടു അടിച്ചു*.",
    "{User2}  ഒരു ചുഴലിക്കാറ്റിൽ പെട്ടു പോയി",
    "{User1} പാത്രം എടുത്ത {user2} {throws}"
    
    )
    